// Generated by ReScript, PLEASE EDIT WITH CARE


var ActivityIndicator = {};

var FlatList = {};

var ReactNativeText = {};

var View = {};

var Button = {};

var ScrollView = {};

export {
  ActivityIndicator ,
  FlatList ,
  ReactNativeText ,
  View ,
  Button ,
  ScrollView ,
  
}
/* No side effect */
