// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function Link(Props) {
  var to = Props.to;
  var children = Props.children;
  var handleClick = React.useCallback((function (ev) {
          ev.stopPropagation();
          ev.preventDefault();
          return RescriptReactRouter.push(to);
        }), [to]);
  return React.createElement("a", {
              href: to,
              onClick: handleClick
            }, children);
}

var make = Link;

export {
  make ,
  
}
/* react Not a pure module */
