// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.bs.js";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as ModuleItem from "./ModuleItem.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactNativeWeb from "react-native-web";

function ModuleList(Props) {
  var json = Props.json;
  var data = React.useMemo((function () {
          var __x = Belt_Option.getWithDefault(Belt_Option.flatMap(Belt_Option.flatMap(Js_json.decodeObject(json), (function (__x) {
                          return Js_dict.get(__x, "modules");
                        })), Js_json.decodeArray), []);
          return __x.sort(Utils.sortBySize);
        }), [json]);
  var partial_arg = Caml_option.some(undefined);
  return React.createElement(ReactNativeWeb.View, {
              style: {
                flex: 1
              },
              children: React.createElement(ReactNativeWeb.FlatList, {
                    data: data,
                    renderItem: (function (param) {
                        return ModuleItem.moduleItem(partial_arg, param);
                      }),
                    style: {
                      flex: 1
                    }
                  })
            });
}

var make = ModuleList;

export {
  make ,
  
}
/* react Not a pure module */
