// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ReactNativeWeb from "react-native-web";

var tabList = [
  "chunks",
  "modules"
];

function Tabs(Props) {
  var currentTab = Props.currentTab;
  var setTab = Props.setTab;
  var isCurrentTabInList = tabList.includes(currentTab);
  return React.createElement(ReactNativeWeb.View, {
              style: {
                flexDirection: "row"
              },
              children: null
            }, tabList.map(function (item, index) {
                  var title = currentTab === item ? "\"" + item + "\"" : item;
                  return React.createElement(ReactNativeWeb.Button, {
                              title: title,
                              onPress: (function (param) {
                                  return Curry._1(setTab, (function (param) {
                                                return item;
                                              }));
                                }),
                              key: String(index)
                            });
                }), isCurrentTabInList ? null : React.createElement(ReactNativeWeb.Button, {
                    title: "\"" + currentTab + "\"",
                    onPress: (function (param) {
                        return Curry._1(setTab, (function (param) {
                                      return currentTab;
                                    }));
                      })
                  }));
}

var make = Tabs;

export {
  tabList ,
  make ,
  
}
/* react Not a pure module */
