// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactNativeWeb from "react-native-web";

var styles = ReactNativeWeb.StyleSheet.create({
      monospaceText: {
        fontFamily: "monospace"
      }
    });

function $$Text(Props) {
  var children = Props.children;
  var styleOpt = Props.style;
  var style = styleOpt !== undefined ? Caml_option.valFromOption(styleOpt) : null;
  return React.createElement(ReactNativeWeb.Text, {
              style: ReactNativeWeb.StyleSheet.flatten([
                    styles.monospaceText,
                    style
                  ]),
              children: children
            });
}

var make = $$Text;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
