// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as AppFilesJs from "./AppFiles.js";
import * as ReactRouterDom from "react-router-dom";

function useStatJSON(prim) {
  return AppFilesJs.useStatJSON();
}

var make = AppFilesJs.ChunkList;

var ChunkList = {
  make: make
};

var make$1 = AppFilesJs.ShowChunk;

var ShowChunk = {
  make: make$1
};

var make$2 = AppFilesJs.ModuleList;

var ModuleList = {
  make: make$2
};

var make$3 = AppFilesJs.ShowModule;

var ShowModule = {
  make: make$3
};

var make$4 = AppFilesJs.Tabs;

var Tabs = {
  make: make$4
};

var styles = ReactNative.StyleSheet.create({
      container: {
        flex: 1,
        backgroundColor: "#fff",
        height: window.innerHeight
      },
      centeredContent: {
        alignItems: "center"
      },
      monospaceText: {
        fontFamily: "monospace"
      }
    });

function App$Text(Props) {
  var children = Props.children;
  var styleOpt = Props.style;
  var style = styleOpt !== undefined ? Caml_option.valFromOption(styleOpt) : null;
  return React.createElement(ReactNative.Text, {
              style: ReactNative.StyleSheet.flatten([
                    styles.monospaceText,
                    style
                  ]),
              children: children
            });
}

var $$Text = {
  make: App$Text
};

function App$LoadedApp(Props) {
  var json = Props.json;
  var match = React.useState(function () {
        return "chunks";
      });
  var setTab = match[1];
  var currentTab = match[0];
  return React.createElement(ReactNative.View, {
              style: styles.container,
              children: null
            }, React.createElement(ReactNative.View, {
                  style: styles.centeredContent,
                  children: null
                }, React.createElement(App$Text, {
                      children: "Open up App.js to start working on your app!"
                    }), React.createElement(ReactRouterDom.Route, {
                      render: (function (param) {
                          return React.createElement(make$4, {
                                      match: param.match,
                                      currentTab: currentTab,
                                      setTab: setTab
                                    });
                        })
                    })), React.createElement(ReactRouterDom.Switch, {
                  children: null
                }, React.createElement(ReactRouterDom.Route, {
                      path: "/",
                      exact: true,
                      render: (function (param) {
                          return React.createElement(make, {
                                      match: param.match,
                                      json: json
                                    });
                        })
                    }), React.createElement(ReactRouterDom.Route, {
                      path: "/chunks",
                      exact: true,
                      render: (function (param) {
                          return React.createElement(make, {
                                      match: param.match,
                                      json: json
                                    });
                        })
                    }), React.createElement(ReactRouterDom.Route, {
                      path: "/chunks/:chunkID",
                      exact: true,
                      render: (function (param) {
                          return React.createElement(make$1, {
                                      match: param.match,
                                      json: json
                                    });
                        })
                    }), React.createElement(ReactRouterDom.Route, {
                      path: "/modules",
                      exact: true,
                      render: (function (param) {
                          return React.createElement(make$2, {
                                      match: param.match,
                                      json: json
                                    });
                        })
                    }), React.createElement(ReactRouterDom.Route, {
                      path: "/modules/:moduleID",
                      exact: true,
                      render: (function (param) {
                          return React.createElement(make$3, {
                                      match: param.match,
                                      json: json
                                    });
                        })
                    }), React.createElement(ReactRouterDom.Route, {
                      path: "/modules/:moduleID/:subModuleIndex",
                      exact: true,
                      render: (function (param) {
                          return React.createElement(make$3, {
                                      match: param.match,
                                      json: json
                                    });
                        })
                    })));
}

var LoadedApp = {
  make: App$LoadedApp
};

function App(Props) {
  var nullableJson = AppFilesJs.useStatJSON();
  window.json = nullableJson;
  console.log("json", nullableJson);
  if (nullableJson == null) {
    return React.createElement(ReactNative.ActivityIndicator, {});
  } else {
    return React.createElement(ReactRouterDom.BrowserRouter, {
                children: React.createElement(App$LoadedApp, {
                      json: nullableJson
                    })
              });
  }
}

var make$5 = App;

var $$default = App;

export {
  useStatJSON ,
  ChunkList ,
  ShowChunk ,
  ModuleList ,
  ShowModule ,
  Tabs ,
  styles ,
  $$Text ,
  LoadedApp ,
  make$5 as make,
  $$default ,
  $$default as default,
  
}
/* make Not a pure module */
