// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as AppFilesJs from "./AppFiles.js";
import * as ReactRouterDom from "react-router-dom";

var ActivityIndicator = {};

var make = AppFilesJs.LoadedApp;

var LoadedApp = {
  make: make
};

function useStatJSON(prim) {
  return AppFilesJs.useStatJSON();
}

function App(Props) {
  var nullableJson = AppFilesJs.useStatJSON();
  window.json = nullableJson;
  console.log("json", nullableJson);
  if (nullableJson == null) {
    return React.createElement(ReactNative.ActivityIndicator, {});
  } else {
    return React.createElement(ReactRouterDom.BrowserRouter, {
                children: React.createElement(make, {
                      json: nullableJson
                    })
              });
  }
}

var make$1 = App;

var $$default = App;

export {
  ActivityIndicator ,
  LoadedApp ,
  useStatJSON ,
  make$1 as make,
  $$default ,
  $$default as default,
  
}
/* make Not a pure module */
